services:

  postgres:
    image: postgres:17
    container_name: postgres-db

    environment:
      POSTGRES_DB: haarlememeer_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    volumes:
      - keycloak_data:/var/lib/keycloak/data

    ports:
      - "9090:8080"

    command:
      - start-dev

volumes:
  postgres_data:
  keycloak_data: