spring:
  application:
    name: haarlememeer-service
    port: 8081
  datasource:
    url: jdbc:postgresql://localhost:5432/haarlememeer_db
    username: admin
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update

      show-sql: true

      properties:
        hibernate:
          format_sql: true

logging:
  level:
    root: INFO
    com.microservices.study: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
  file:
    name: logs/haarlememeer-service.log
